import { ENV } from "../config/env";

export async function generateReply(
  message: string
): Promise<string> {

  if (!ENV.GEMINI_API_KEY) {
    return "Gemini API Key Missing";
  }

  /*
     Real API call
     next batch
  */

  return `AI Reply:

${message}

(Generated by Gemini)`;
}